<?php

namespace minervis\plugins\LPFixx;

use minervis\plugins\LPFixx\Job\Repository as JobsRepository;
use minervis\plugins\LPFixx\Utils\LPFixxTrait;
use ilLPFixxPlugin;
use minervis\plugins\LPFixx\Log\Repository as LogRepository;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.10.0
 *
 * @package minervis\plugins\LPFixx
 *
 * @author Jephte Abijuru <jephte.abijuru@minervis.com>
 */
final class Repository
{

    use LPFixxTrait;

    const PLUGIN_CLASS_NAME = ilLPFixxPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    public function dropTables() : void
    {

        $this->jobs()->dropTables();
    }



    public function installTables() : void
    {

        $this->jobs()->installTables();
    }


    /**
     * @return JobsRepository
     */
    public function jobs() : JobsRepository
    {
        return JobsRepository::getInstance();
    }
}
